# This file was generated by GoReleaser. DO NOT EDIT.
cask "engram" do
  version "2.2.1"

  on_macos do
    on_intel do
      sha256 "06ce525c0323a992ffc6cce1b4d3f48b19c16eaf69734ea4942cf6bd6abbaa6b"
      url "https://github.com/yersonargotev/engram/releases/download/v#{version}/engram_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "8ad69bb8ef7ea072bd8142fc98ef91b98d73217c1a302df1f932ab7f8378fb83"
      url "https://github.com/yersonargotev/engram/releases/download/v#{version}/engram_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c6114b900c017727c6cd1449c7e42a9f240c4c1f4f21a674e40400d0e130820c"
      url "https://github.com/yersonargotev/engram/releases/download/v#{version}/engram_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "aa9b83ab40a3659b9d7ceb6c74cce05545f5d75b191280981aa064e0140ae47d"
      url "https://github.com/yersonargotev/engram/releases/download/v#{version}/engram_#{version}_linux_arm64.tar.gz"
    end
  end

  name "engram"
  desc "Persistent memory for AI coding agents. Agent-agnostic, single binary, zero dependencies."
  homepage "https://github.com/yersonargotev/engram"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "engram"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/engram"]
    end
  end

  # No zap stanza required

end
