# This file was generated by GoReleaser. DO NOT EDIT.
cask "engram" do
  version "3.5.0"

  on_macos do
    on_arm do
      sha256 "778dfbe32eedb994887ae8b2413c3990256201ed28a0159852282dd9ef834fb4"
      url "https://github.com/yersonargotev/engram/releases/download/v#{version}/engram_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "eee40668a349d32c6a2b8483c4b66b0aad91969cb896d89dd8f10113f60aa5ef"
      url "https://github.com/yersonargotev/engram/releases/download/v#{version}/engram_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "a259d749e1511ab807571925cbdb939ce9199f005f1812a2c1d377109122ed90"
      url "https://github.com/yersonargotev/engram/releases/download/v#{version}/engram_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "6d9b2f5e65fd41e7eb1d5a65d4074bc6f65d6a6c243387ac3fd771d361c6682c"
      url "https://github.com/yersonargotev/engram/releases/download/v#{version}/engram_#{version}_linux_amd64.tar.gz"
    end
  end

  name "engram"
  desc "Persistent memory for AI coding agents. Agent-agnostic, single binary, zero dependencies."
  homepage "https://github.com/yersonargotev/engram"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "engram"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/engram"]
    end
  end

  # No zap stanza required
end
