# This file was generated by GoReleaser. DO NOT EDIT.
cask "engram" do
  version "3.3.1"

  on_macos do
    on_arm do
      sha256 "576f76527b4859d57726f62fd8320beca90d8ba5ce5deaacf7086d138601ed08"
      url "https://github.com/yersonargotev/engram/releases/download/v#{version}/engram_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "74268424be3f45394bfab93af61e010d38be073f9c432d50b82468f5c8dcc9ee"
      url "https://github.com/yersonargotev/engram/releases/download/v#{version}/engram_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "165f44ee3165d50a8a39938fe4e79f59e97ee10c24f46e2208279d0f05b16647"
      url "https://github.com/yersonargotev/engram/releases/download/v#{version}/engram_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "596bf05bcc15cc97d832017a37f276e8c3876e226eab3d171c210c864968ec34"
      url "https://github.com/yersonargotev/engram/releases/download/v#{version}/engram_#{version}_linux_amd64.tar.gz"
    end
  end

  name "engram"
  desc "Persistent memory for AI coding agents. Agent-agnostic, single binary, zero dependencies."
  homepage "https://github.com/yersonargotev/engram"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "engram"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/engram"]
    end
  end

  # No zap stanza required
end
